//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardware
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int Id { get; set; }
        public int Manufacturer { get; set; }
        public string Name { get; set; }
        public int MeasureUnit { get; set; }
        public double Price { get; set; }
        public int Category { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
