//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardware
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HardwareEntities : DbContext
    {
        public HardwareEntities()
            : base("name=HardwareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Deals> Deals { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Sellers> Sellers { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
